#!/bin/bash
set -x
echo “post-commit $@”
commit_msg=$(cat .git/COMMIT_EDITMSG)
pwd
. ./.git/hooks/log_util.sh

# 生成密钥
if [ ! -d "./.git/hooks/keyRoot" ]; then
    ./.git/hooks/git_ssl.sh create_key_pairs - - -
    ret=$?
    if [ $ret -ne 0 ]; then
        log_error "${LINENO}:  failed : $ret.EXIT"
        git reset --hard
        exit 1
    fi
    
fi

# 添加
./.git/hooks/git_ssl.sh git_add_changes `cd .; pwd`
ret=$?
if [ $ret -ne 0 ]; then
    log_error "${LINENO}:  failed : $ret.EXIT"
    git reset --hard
    exit 1
fi 

./.git/hooks/git_ssl.sh compress_and_encrypt `cd .; pwd` - -
ret=$?
if [ $ret -ne 0 ]; then
    log_error "${LINENO}:  failed : $ret.EXIT"
    git reset --hard
    exit 1
fi 

git add -u
ret=$?
if [ $ret -ne 0 ]; then
    log_error "${LINENO}:  failed : $ret.EXIT"
    git reset --hard
    exit 1
fi 
git commit -m "$commit_msg"
ret=$?
if [ $ret -ne 0 ]; then
    log_error "${LINENO}:  failed : $ret.EXIT"
    git reset --hard
    exit 1
fi 

exit 0